name: Lepvp
version: '1.18'
main: me.maanraj514.Lepvp
api-version: 1.17
author: me.Maanraj514
softdepend:
  - SlimeWorldManager
commands:
  setLobby:
    usage: /<command>
  arena:
    usage: /<command>
    aliases:
      - a
  duels:
    usage: /<command>
  join:
    usage: /<command>
    aliases:
      - j
  quit:
    usage: /<command>
    aliases:
      - q
  randomJoin:
    usage: /<command>
    aliases:
      - rj
permissions:
  lepvp.admin:
    description: The admin permission for the plugin.